server {
    listen 80;
    server_name vsngrp-fec.prothegee.dev;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name vsngrp-fec.prothegee.dev;

    ssl_certificate /etc/letsencrypt/live/vsngrp-fec.prothegee.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vsngrp-fec.prothegee.dev/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:9003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
