name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: ./run-tests.sh

      - name: docker build check
        run: docker build --build-arg GIT_SHA=${{ github.sha }} -t vsngrp-core-fe:ci .
